name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - master
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd  userapi
        npm install

    - name: Run test
      run: |
        cd  userapi
        npm test
  deploy:
    needs: build-and-test # La phase "deploy" ne démarre que si "build-and-test" réussit
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Étape 3 : Déploiement
      - name: Deploy Application
        env:
          NODE_ENV: production
        run: |
          cd userapi
          npm install
          npm run start